### ISSUE TITLE
Frame Capture Timing Out

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv#2200]
https://forums.openmv.io/t/frame-capture-randomly-timing-out/9482/9

Need to investigate this issue.

**Comment by justfone** [comment]
For info, I'm experiencing the same issue as reported in the forum post, almost identical situation as below : 

- RT1062 running on battery or USB
- Wake from deep sleep (time or external trigger)
- Look for QR codes for 5 seconds
- Dump details of any QR found out via UART
- Back to deep sleep

Works perfectly for random periods of time and then starts throwing "Frame Capture TimeOut" exception, if the exception is handled and system is put back into deep sleep then starts working fine again on next wake up.

Initial sensor config is as below


```
sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.VGA)
sensor.set_auto_gain(False)
sensor.set_framebuffers(3)
```

**Comment by kwagyeman** [comment]
[firmware.zip](https://github.com/user-attachments/files/15520099/firmware.zip)

Can you test out this firmware?

**Comment by iabdalkader** [comment]
It's been a while since you reported this issue. I just released a new firmware, v4.5.5, last week, with some important fixes to FB cache. Can you please test the stable v4.5.5 see if it fixes the issue before the other custom firmware above ? Also if you can, please post a script that we can use to reproduce the issue.

**Comment by justfone** [comment]
I didn't report the initial issue, I just came across it when I experienced the same problem, I can confirm though that we updated to 4.5.5 last week and were still experiencing it. 

I'm busy on another project for a few days, but I will give the custom firmware a try and generate some minimal code that produces the issue once I get back on this later in the week

**Comment by kwagyeman** [comment]
Thanks, this is P0 debugging for us.

**Comment by justfone** [comment]
I've tried the custom firmware you provided (4.5.6) but unfortunately the exception is still thrown after a period of time (random, can be minutes or hours)

This is the minimal code we stripped back for testing, which should reproduce the issue

```
import time
from machine import UART, deepsleep, LED, WDT, reset_cause, reset
import machine
import network
import sensor

TIMEOUT = 10
uart = UART(1, 115200, timeout_char=200)

#camera stuff
sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.VGA)
sensor.set_auto_gain(False)
sensor.set_framebuffers(3)

#LEDS used for camera indication
led_ok = LED("LED_GREEN")
led_ok.off()
led_cam_on = LED("LED_BLUE")
led_cam_on.on()

uart.write(f'Start Scan at {time.time()}\r\n')
done = False
start = time.time()

try:
    sensor.skip_frames(time=100)
    while not done and (start + TIMEOUT >= time.time()):
        led_cam_on.toggle()
        led_ok.off()
        img = sensor.snapshot()
        img.lens_corr(1.8)
        for code in img.find_qrcodes():
            led_cam_on.off()
            led_ok.on()
            time.sleep_ms(250)
            led_ok.off()
            uart.write(f"Payload = {code.payload()}\r\n")
            done = True

    led_cam_on.off()
    led_ok.off()
    sensor.shutdown(True)

    uart.write(f'Going to sleep at {time.time()}\r\n')
    while not uart.txdone():
         time.sleep_ms(50)

    deepsleep(20000)

except Exception as e:
    uart.write(f"Exception = {e} at {time.time()}\r\n")

```

**Comment by iabdalkader** [comment]
This issue has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/issue-with-imageio-write-py-example-on-rt1062-stucks-writing-to-sd-card/9662/2

**Comment by kdarras** [comment]
I obtained the same error with my script when running `sensor.skip_frames(time=2000)` on the RT1062 (4.7.0).
Trying to set the frame buffer to contain 3 frames before the frame skipping solved the problem, even though get_framebuffers() told me that it was still just 1...
I could try making a reproducible example, but the error is sporadic and it isn't resolved just by powering down and reconnecting the board.

**Comment by kwagyeman** [comment]
Can you run the latest firmware via Tools->Install Latest Dev Release? I enabled full offload on the camera with the latest dev release which significantly reduces the number of interrupts the CPU receives to get a frame in. It should be rock solid.

**Comment by kdarras** [comment]
Just installed the latest dev release, but ran into another problem further down the code:

<img width="948" height="170" alt="Image" src="https://github.com/user-attachments/assets/8ab90378-3bae-42e8-9e83-0f154c152ea3" />
Previously this command didn't complain when I tried setting a buffer for three frames.
When I set it to 1 now, it proceeds.

So I haven't encountered "Frame capture running out" anymore... it seems solved as far as I can tell with my limited testing.

**Comment by kwagyeman** [comment]
The frame buffer architecture was changed around, and buffers have slightly different memory allocation sizes. That shouldn't fail unless you were pushing the system such that RAM was extremely limited. The previous code was more forgiving and would have allowed any buffer requested, shurnk buffers such that they all fit given the count, and then cropped images to fit the smaller buffers. The new code just tries to allocate the requested count given the set resolution and if it doesn't fit it errors out.
